### ISSUE TITLE
Need help when navigating

### ISSUE THREAD

**Issue by najmisyahir** [mapbox/mapbox-navigation-hud-demo#1]
Hi, currently i've implemented your code for my navigation, but currently i got an error on 
`maneuverImage.setImageResource(obtainManeuverResource(upComingStep));`

the error is 
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference`

any idea how to solve this, btw great repo dude.

**Comment by danesfeder** [comment]
Hey @najmisyahir, you're using the same navigation code from this repo?  It sounds like your `ImageView` isn't being bound before you try to set the image resource for the first time.

**Comment by najmisyahir** [comment]
Solve it by messing around with build gradle for the butterknife thx btw @danesfeder
